### ISSUE TITLE
regs value not update

### ISSUE THREAD

**Issue by undefPtr** [teemu-l/execution-trace-viewer#4]
hi~
I found regs value not update immediately.When push instruction finish,esp value has a color, but not update value immediately.
![image](https://user-images.githubusercontent.com/9676660/72552897-b89ff600-38d2-11ea-89e0-80ca1deeec21.png)

**Comment by teemu-l** [comment]
Hi

I think that is not a bug. Reg values you see are before the execution of the current row. So the highlighted esp reg is modified on row <i>#</i>2 and you should see the new value on row <i>#</i>3.

**Comment by undefPtr** [comment]
I know this,thanks for your reply. I have pactched the source code for myself and thanks for your job
